### ISSUE TITLE
MVVM的Demo

### ISSUE THREAD

**Issue by CrazyCoderShi** [iOS-Swift-Developers/Swift#7]
会考虑加入Rx系列进行demo演示么 ？
其实我是加入群失败，来这里提个issues，联系群主的 😂

**Comment by xiaohange** [comment]
@CrazyCoderShi (手机加)QQ群:446310206 | 426087546  需要付费才能加入. 如果有需要会逐渐加入RXSwift-MVVM

**Comment by CrazyCoderShi** [comment]
@xiaohange 两个都需要付费了？付费多少 ？

**Comment by xiaohange** [comment]
@CrazyCoderShi 使用手机加群的时候可以看到呀, 介意收费还请勿加!

**Comment by grafeoy** [comment]
请问，为什麽我会收到你们之间沟通的信件?

2018/2/24 下午1:20，"HanJunqiang" <notifications@github.com>寫道：

**Comment by xiaohange** [comment]
@grafeoy 估计是广播吧
